import { requireChatGPTUser } from "@/app/chatgpt-auth";
import { listMemberships, upsertIdentity } from "@/db/access";

export const dynamic = "force-dynamic";

export default async function DepartmentPortal() {
  const user = await requireChatGPTUser("/portal");
  await upsertIdentity(user);
  const memberships = await listMemberships(user.userId);
  return <main className="access-shell"><header className="access-header"><a href="/" className="access-brand">PrePlan <span>360</span><small>Department access</small></a><div className="access-account"><span>{user.displayName}</span><form method="post" action="/api/member/logout"><button className="owner-signout" type="submit">Sign out</button></form></div></header><section className="access-page"><div className="access-kicker">DEPARTMENT PORTAL</div><h1>Welcome back.</h1><p className="access-lead">Open your department’s branded web app. Bookmark that direct app page or add it to the device home screen for a permanent shortcut.</p>{memberships.length ? <div className="access-grid">{memberships.map((membership) => { const admin = ["department_admin", "chief_admin"].includes(membership.membership_role); return <article className="access-card department-entry" key={membership.id} style={{ borderTopColor: membership.brand_primary }}><div className="portal-dept-logo">{membership.logo_key ? <img src={`/api/departments/${membership.id}/logo`} alt=""/> : <span style={{ background: membership.brand_primary }}>{membership.name.slice(0, 2).toUpperCase()}</span>}</div><div className="access-card-top"><span className="access-dot"/><b>{membership.membership_role.replaceAll("_", " ")}</b></div><h2>{membership.app_title || membership.name}</h2><p>{membership.station_count} station{membership.station_count === 1 ? "" : "s"} · {membership.vehicle_count} vehicles</p><div className="portal-card-actions"><a className="access-primary" href={`/d/${membership.slug}`}>Open department app <span>→</span></a>{admin ? <a className="access-secondary" href={`/departments/${membership.id}`}>Build & branding</a> : null}</div></article>; })}</div> : <div className="access-empty"><div><span>FIRST-TIME SIGN IN</span><h2>Request department access</h2><p>Your verified ChatGPT identity will be attached to the request. The platform owner must approve access before any department app opens.</p></div><form method="post" action="/api/access-requests" className="access-form"><label>Department name<input required name="department_name" placeholder="Department or district name"/></label><label>Requested role<select name="requested_role" defaultValue="department_admin"><option value="department_admin">Department administrator</option><option value="chief_admin">Chief administrator</option><option value="viewer">View only</option></select></label><label className="wide">Request note<textarea name="note" rows={3} placeholder="Your role and why access is needed"/></label><button className="access-primary" type="submit">Send access request <span>→</span></button></form></div>}<div className="access-note"><b>Secure access boundary</b><span>Signing in identifies you. Department membership controls which branded app you can open; it never grants access to other departments.</span></div></section></main>;
}
