"use client";

import { useMemo, useState } from "react";
import { foundationModules, liveBoardPanels, liveBoardWidgets, type FoundationModuleKey, type FoundationSettings, type LiveBoardWidth } from "@/db/foundation";

export default function FoundationEditor({ settings, scopeName }: { settings: FoundationSettings; scopeName: string }) {
  const [order, setOrder] = useState<FoundationModuleKey[]>(settings.module_order);
  const [boardOrder, setBoardOrder] = useState(settings.live_board_order);
  const [boardHidden, setBoardHidden] = useState(settings.live_board_hidden);
  const [boardWidths, setBoardWidths] = useState(settings.live_board_widths);
  const label = useMemo(() => new Map(foundationModules.map((module) => [module.key, module.label])), []);
  const boardLabel = useMemo(() => new Map([
    ...liveBoardWidgets.map((widget) => [widget.key, widget.label] as const),
    ...settings.live_board_external_links.map((link) => [link.id, link.title] as const),
  ]), [settings.live_board_external_links]);

  function moveModule(index: number, direction: -1 | 1) {
    const target = index + direction;
    if (target < 0 || target >= order.length) return;
    setOrder((current) => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  }
  function moveBoard(index: number, direction: -1 | 1) {
    const target = index + direction;
    if (target < 0 || target >= boardOrder.length) return;
    setBoardOrder((current) => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  }

  return <form className="foundation-form" method="post" action="/api/owner/foundation">
    <input type="hidden" name="scope" value={settings.scope}/><input type="hidden" name="department_id" value={settings.department_id || ""}/><input type="hidden" name="module_order" value={order.join(",")}/><input type="hidden" name="live_board_order" value={boardOrder.join(",")}/><input type="hidden" name="live_board_visibility_marker" value="yes"/>
    <section className="foundation-section"><div className="foundation-section-head"><div><span>MODULE FOUNDATION</span><h2>Visibility and order</h2><p>Move modules into the order this department should use. Hidden modules disappear from the actual department navigation.</p></div><b>{scopeName}</b></div><div className="foundation-module-list">{order.map((key, index) => <article key={key}><span>{String(index + 1).padStart(2, "0")}</span><b>{label.get(key)}</b><div><button type="button" onClick={() => moveModule(index, -1)} disabled={index === 0} aria-label={`Move ${label.get(key)} up`}>↑</button><button type="button" onClick={() => moveModule(index, 1)} disabled={index === order.length - 1} aria-label={`Move ${label.get(key)} down`}>↓</button><label><input type="checkbox" name="hidden_modules" value={key} defaultChecked={settings.hidden_modules.includes(key)} disabled={key === "dashboard"}/>Hide</label></div></article>)}</div></section>

    <section className="foundation-section"><div className="foundation-section-head"><div><span>LIVE OPERATIONS FOUNDATION</span><h2>The inherited board</h2><p>This is the saved version of the usable demo board. Every department starts with it, then authorized department users can save their own layout and display sources.</p></div><b>DEMO BASE</b></div><div className="foundation-board-grid">
      <section><h3>Identity and timing</h3><label>Board title<input name="live_board_title" required maxLength={80} defaultValue={settings.live_board_title}/></label><div className="foundation-fields"><label>Information rotation (seconds)<input required type="number" min="5" max="300" name="board_rotation_seconds" defaultValue={settings.board_rotation_seconds}/></label><label>Response page duration (seconds)<input required type="number" min="5" max="600" name="response_duration_seconds" defaultValue={settings.response_duration_seconds}/></label></div></section>
      <section><h3>Station information rotation</h3><div className="foundation-board-checks">{liveBoardPanels.map((panel) => <label key={panel.key}><input type="checkbox" name="live_board_panels" value={panel.key} defaultChecked={settings.live_board_panels.includes(panel.key)}/>{panel.label}</label>)}</div></section>
      <section className="wide"><h3>Board layout</h3><div className="foundation-board-layout">{boardOrder.map((key, index) => <article key={key}><label><input type="checkbox" name="live_board_visible" value={key} checked={!boardHidden.includes(key)} onChange={(event) => setBoardHidden(event.target.checked ? boardHidden.filter((value) => value !== key) : [...boardHidden, key])}/><b>{boardLabel.get(key) || key}</b></label><select name={`live_board_width_${key}`} value={boardWidths[key] || "half"} onChange={(event) => setBoardWidths((current) => ({ ...current, [key]: event.target.value as LiveBoardWidth }))}><option value="third">One third</option><option value="half">Half</option><option value="full">Full</option></select><button type="button" onClick={() => moveBoard(index, -1)} disabled={index === 0}>Up</button><button type="button" onClick={() => moveBoard(index, 1)} disabled={index === boardOrder.length - 1}>Down</button></article>)}</div><small>Checked cards are visible. External links are added below and join this layout after the first save.</small></section>
      <section className="wide"><h3>Weather, radar, and outside links</h3><div className="foundation-board-sources"><label>Weather display link<input name="live_board_weather_url" type="url" placeholder="https://" defaultValue={settings.live_board_weather_url}/></label><label>Weather alerts link<input name="live_board_alerts_url" type="url" placeholder="https://" defaultValue={settings.live_board_alerts_url}/></label><label>Radar link<input name="live_board_radar_url" type="url" placeholder="https://" defaultValue={settings.live_board_radar_url}/></label><label>Radar refresh minutes<input name="live_board_radar_refresh_minutes" type="number" min={1} max={120} defaultValue={settings.live_board_radar_refresh_minutes}/></label><label>Weather amount<select name="live_board_forecast_detail" defaultValue={settings.live_board_forecast_detail}><option value="current">Current conditions</option><option value="3">3-day view</option><option value="7">7-day view</option></select></label><label className="wide">External displays · one per line<textarea name="live_board_external_links" rows={4} placeholder="Traffic camera | https://example.com" defaultValue={settings.live_board_external_links.map((entry) => `${entry.title} | ${entry.url}`).join("\n")}/></label></div><small>Outside links open separately. Do not save usernames, passwords, secret keys, or tokens here.</small></section>
    </div></section>

    <div className="foundation-rule-grid"><section className="foundation-section"><span>DISPLAY FOUNDATION</span><h2>Board behavior</h2><p className="foundation-help">The saved Live Operations layout above replaces the former blank build card. Departments inherit it until they save an override.</p></section><section className="foundation-section"><span>SCHEDULING</span><h2>Shift foundation</h2><div className="foundation-fields three"><label>Hours on<input required type="number" min="1" max="168" name="shift_hours_on" defaultValue={settings.shift_hours_on}/></label><label>Hours off<input required type="number" min="0" max="336" name="shift_hours_off" defaultValue={settings.shift_hours_off}/></label><label>Start time<input required type="time" name="shift_start_time" defaultValue={settings.shift_start_time}/></label><label className="wide">Scheduling rules and notes<textarea name="scheduling_notes" rows={5} maxLength={4000} defaultValue={settings.scheduling_notes}/></label></div></section><section className="foundation-section"><span>OVERTIME</span><h2>Overtime foundation</h2><div className="foundation-fields"><label>Work period (days)<input required type="number" min="1" max="366" name="overtime_period_days" defaultValue={settings.overtime_period_days}/></label><label>Threshold hours<input required type="number" min="1" max="1000" name="overtime_threshold_hours" defaultValue={settings.overtime_threshold_hours}/></label><label className="wide">Assignment rule<input required name="overtime_assignment_rule" maxLength={240} defaultValue={settings.overtime_assignment_rule}/></label><label className="wide">Overtime rules and notes<textarea name="overtime_notes" rows={5} maxLength={4000} defaultValue={settings.overtime_notes}/></label></div></section></div>
    <div className="foundation-actions"><button className="access-primary" type="submit" name="action" value="save">Save {settings.scope === "master" ? "owner foundation" : "department override"}</button>{settings.scope === "department" && settings.is_override ? <button className="access-secondary" type="submit" name="action" value="inherit">Remove override and inherit master</button> : null}</div>
  </form>;
}
