"use client";

import { useMemo, useState } from "react";
import { foundationModules, type FoundationModuleKey, type FoundationSettings } from "@/db/foundation";

export default function FoundationEditor({ settings, scopeName }: { settings: FoundationSettings; scopeName: string }) {
  const [order, setOrder] = useState<FoundationModuleKey[]>(settings.module_order);
  const label = useMemo(() => new Map(foundationModules.map((module) => [module.key, module.label])), []);
  function move(index: number, direction: -1 | 1) {
    const target = index + direction;
    if (target < 0 || target >= order.length) return;
    setOrder((current) => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  }
  return <form className="foundation-form" method="post" action="/api/owner/foundation">
    <input type="hidden" name="scope" value={settings.scope}/><input type="hidden" name="department_id" value={settings.department_id || ""}/><input type="hidden" name="module_order" value={order.join(",")}/>
    <section className="foundation-section"><div className="foundation-section-head"><div><span>MODULE FOUNDATION</span><h2>Visibility and order</h2><p>Move modules into the order this department should use. Hidden modules disappear from the actual department navigation.</p></div><b>{scopeName}</b></div><div className="foundation-module-list">{order.map((key, index) => <article key={key}><span>{String(index + 1).padStart(2, "0")}</span><b>{label.get(key)}</b><div><button type="button" onClick={() => move(index, -1)} disabled={index === 0} aria-label={`Move ${label.get(key)} up`}>↑</button><button type="button" onClick={() => move(index, 1)} disabled={index === order.length - 1} aria-label={`Move ${label.get(key)} down`}>↓</button><label><input type="checkbox" name="hidden_modules" value={key} defaultChecked={settings.hidden_modules.includes(key)} disabled={key === "dashboard"}/>Hide</label></div></article>)}</div></section>
    <div className="foundation-rule-grid"><section className="foundation-section"><span>DISPLAY TIMERS</span><h2>Live board timing</h2><div className="foundation-fields"><label>Information rotation (seconds)<input required type="number" min="3" max="300" name="board_rotation_seconds" defaultValue={settings.board_rotation_seconds}/></label><label>Response page duration (seconds)<input required type="number" min="3" max="600" name="response_duration_seconds" defaultValue={settings.response_duration_seconds}/></label></div></section><section className="foundation-section"><span>SCHEDULING</span><h2>Shift foundation</h2><div className="foundation-fields three"><label>Hours on<input required type="number" min="1" max="168" name="shift_hours_on" defaultValue={settings.shift_hours_on}/></label><label>Hours off<input required type="number" min="0" max="336" name="shift_hours_off" defaultValue={settings.shift_hours_off}/></label><label>Start time<input required type="time" name="shift_start_time" defaultValue={settings.shift_start_time}/></label><label className="wide">Scheduling rules and notes<textarea name="scheduling_notes" rows={5} maxLength={4000} defaultValue={settings.scheduling_notes}/></label></div></section><section className="foundation-section"><span>OVERTIME</span><h2>Overtime foundation</h2><div className="foundation-fields"><label>Work period (days)<input required type="number" min="1" max="366" name="overtime_period_days" defaultValue={settings.overtime_period_days}/></label><label>Threshold hours<input required type="number" min="1" max="1000" name="overtime_threshold_hours" defaultValue={settings.overtime_threshold_hours}/></label><label className="wide">Assignment rule<input required name="overtime_assignment_rule" maxLength={240} defaultValue={settings.overtime_assignment_rule}/></label><label className="wide">Overtime rules and notes<textarea name="overtime_notes" rows={5} maxLength={4000} defaultValue={settings.overtime_notes}/></label></div></section></div>
    <div className="foundation-actions"><button className="access-primary" type="submit" name="action" value="save">Save {settings.scope === "master" ? "owner foundation" : "department override"}</button>{settings.scope === "department" && settings.is_override ? <button className="access-secondary" type="submit" name="action" value="inherit">Remove override and inherit master</button> : null}</div>
  </form>;
}
