import AssetCapture from "./asset-capture";
import {
  getDepartmentAsset,
  listAssetMaintenance,
  listAssetResources,
  listDepartmentAssets,
  type AssetEvent,
  type Department,
  type DepartmentAsset,
} from "@/db/access";

export default async function AssetManager({ department, selectedAssetId = "", editable, supportSessionId = "" }: { department: Department; selectedAssetId?: string; editable: boolean; supportSessionId?: string }) {
  const assets = await listDepartmentAssets(department.id);
  const selected = selectedAssetId ? await getDepartmentAsset(department.id, selectedAssetId) : assets[0] || null;
  const [resources, maintenance] = selected ? await Promise.all([listAssetResources(department.id, selected.id), listAssetMaintenance(department.id, selected.id)]) : [[], []];
  const support = supportSessionId ? `&support=${encodeURIComponent(supportSessionId)}` : "";
  const counts = {
    vehicles: assets.filter((asset) => asset.asset_type === "vehicle").length,
    equipment: assets.filter((asset) => asset.asset_type === "equipment").length,
    attention: assets.filter((asset) => ["out_of_service", "maintenance"].includes(asset.status)).length,
  };

  return <div className="asset-workspace">
    <div className="asset-summary"><article><span>Apparatus / vehicles</span><b>{counts.vehicles}</b></article><article><span>Equipment records</span><b>{counts.equipment}</b></article><article className={counts.attention ? "attention" : ""}><span>Needs attention</span><b>{counts.attention}</b></article><article><span>Department records</span><b>{assets.length}</b></article></div>
    {editable ? <AssetCapture departmentId={department.id} supportSessionId={supportSessionId}/> : <div className="asset-view-only"><b>View-only apparatus workspace</b><span>A department administrator—or an owner inside a logged support session—can add or change records.</span></div>}
    <div className="asset-library"><aside><div className="asset-library-head"><span>ASSET REGISTER</span><b>{assets.length} saved</b></div>{assets.length ? <div className="asset-list">{assets.map((asset) => <a className={selected?.id === asset.id ? "active" : ""} href={`/d/${department.slug}?module=fleet&asset=${asset.id}${support}`} key={asset.id}><span className={`asset-kind ${asset.asset_type}`}>{asset.asset_type === "vehicle" ? "VEH" : "EQ"}</span><div><b>{asset.name}</b><small>{[asset.unit_number, asset.manufacturer, asset.model].filter(Boolean).join(" · ") || "Identity not completed"}</small></div><i className={asset.status}/></a>)}</div> : <div className="asset-none">No apparatus or equipment records yet.</div>}</aside>
      <section>{selected ? <AssetDetail department={department} asset={selected} resources={resources} maintenance={maintenance} editable={editable} supportSessionId={supportSessionId}/> : <div className="asset-detail-empty"><span>+</span><h2>Add the first department asset.</h2><p>Use the camera or manual entry above. No sample apparatus or equipment is created for a real department.</p></div>}</section>
    </div>
  </div>;
}

export function AssetDetail({ department, asset, resources, maintenance, events = [], editable, supportSessionId, recordMode = false }: { department: Department; asset: DepartmentAsset; resources: Awaited<ReturnType<typeof listAssetResources>>; maintenance: Awaited<ReturnType<typeof listAssetMaintenance>>; events?: AssetEvent[]; editable: boolean; supportSessionId: string; recordMode?: boolean }) {
  const identity = [asset.model_year, asset.manufacturer, asset.model].filter(Boolean).join(" ");
  const searchBase = [asset.manufacturer, asset.model, asset.model_year, asset.category].filter(Boolean).join(" ");
  const searches = [
    ["Official manuals", `${searchBase} official service operator manual PDF`],
    ["Parts catalogs", `${searchBase} official parts catalog`],
    ["Maintenance guidance", `${searchBase} manufacturer maintenance schedule`],
    ["Repair information", `${searchBase} service repair troubleshooting`],
  ];
  if (asset.barcode) searches.push(["Search scanned code", `"${asset.barcode}" equipment manual parts`]);
  const action = `/api/departments/${department.id}/assets/${asset.id}`;
  const support = supportSessionId ? `?support=${encodeURIComponent(supportSessionId)}` : "";
  const recordPath = `/d/${department.slug}/assets/${asset.id}${support}`;
  const returnTo = recordMode ? recordPath : `/d/${department.slug}?module=fleet&asset=${asset.id}${supportSessionId ? `&support=${encodeURIComponent(supportSessionId)}` : ""}`;

  return <div className="asset-detail">
    <div className="asset-detail-head"><div><span>{asset.asset_type.toUpperCase()} · {asset.status.replaceAll("_", " ")}</span><h2>{asset.name}</h2><p>{identity || asset.category || "Identity details not completed"}</p></div><div className="asset-detail-actions"><span className={`asset-status ${asset.status}`}>{asset.status.replaceAll("_", " ")}</span>{recordMode ? null : <a className="asset-record-link" href={recordPath}>Open full record →</a>}</div></div>
    <div className="asset-facts"><div><span>Permanent record</span><b>{asset.id}</b></div><div><span>Unit / asset</span><b>{asset.unit_number || "Not set"}</b></div><div><span>VIN</span><b>{asset.vin || "Not set"}</b></div><div><span>Barcode</span><b>{asset.barcode || "Not set"}</b></div><div><span>Serial</span><b>{asset.serial_number || "Not set"}</b></div><div><span>Location</span><b>{asset.location || "Not set"}</b></div><div><span>VIN source</span><b>{asset.vin_source || "Manual entry"}</b></div><div><span>Odometer</span><b>{asset.odometer ?? "Not set"}</b></div><div><span>Engine / operating hours</span><b>{asset.engine_hours ?? "Not set"}</b></div></div>
    {editable ? <form className="asset-reading-form" method="post" action={action}><input type="hidden" name="action" value="readings"/><input type="hidden" name="support_session_id" value={supportSessionId}/><input type="hidden" name="return_to" value={returnTo}/><label>Status<select name="status" defaultValue={asset.status}><option value="in_service">In service</option><option value="reserve">Reserve</option><option value="maintenance">Maintenance</option><option value="out_of_service">Out of service</option><option value="retired">Retired</option></select></label><label>Odometer<input type="number" inputMode="numeric" min="0" name="odometer" defaultValue={asset.odometer ?? ""}/></label><label>Engine / operating hours<input type="number" inputMode="numeric" min="0" name="engine_hours" defaultValue={asset.engine_hours ?? ""}/></label><label className="wide">Maintenance notes<textarea name="maintenance_notes" rows={2} defaultValue={asset.maintenance_notes}/></label><button type="submit">Save status and readings</button></form> : null}
    <div className="asset-search-panel"><div><span>WEB RESEARCH</span><h3>Find the right source</h3><p>Search links are suggestions. Review the manufacturer, model, revision, and applicability before saving anything to the department record.</p></div><div>{searches.map(([label, query]) => <a key={label} href={`https://www.google.com/search?q=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer">{label}<span>↗</span></a>)}{asset.vin ? <a href={`https://www.nhtsa.gov/recalls?vin=${encodeURIComponent(asset.vin)}`} target="_blank" rel="noreferrer">NHTSA recall lookup<span>↗</span></a> : null}</div></div>
    <section className="asset-subsection"><div className="asset-subhead"><div><span>REVIEWED RESOURCES</span><h3>Manuals, parts, warranty, and service</h3></div><b>{resources.length + (asset.manual_url ? 1 : 0) + (asset.parts_url ? 1 : 0)} links</b></div><div className="resource-list">{asset.manual_url ? <a href={asset.manual_url} target="_blank" rel="noreferrer"><span>MANUAL</span><b>Official manual</b><small>Saved with asset</small></a> : null}{asset.parts_url ? <a href={asset.parts_url} target="_blank" rel="noreferrer"><span>PARTS</span><b>Parts catalog</b><small>Saved with asset</small></a> : null}{resources.map((resource) => <a href={resource.url} target="_blank" rel="noreferrer" key={resource.id}><span>{resource.resource_type}</span><b>{resource.label}</b><small>Reviewed department link</small></a>)}{!resources.length && !asset.manual_url && !asset.parts_url ? <p>No reviewed resources saved yet.</p> : null}</div>{editable ? <form className="asset-inline-form" method="post" action={action}><input type="hidden" name="action" value="resource"/><input type="hidden" name="support_session_id" value={supportSessionId}/><input type="hidden" name="return_to" value={returnTo}/><select name="resource_type" defaultValue="manual"><option value="manual">Manual</option><option value="parts">Parts</option><option value="service">Service</option><option value="warranty">Warranty</option><option value="recall">Recall</option><option value="other">Other</option></select><input required name="label" placeholder="Reviewed link label"/><input required type="url" name="url" placeholder="https://…"/><button type="submit">Save reviewed link</button></form> : null}</section>
    <section className="asset-subsection"><div className="asset-subhead"><div><span>MAINTENANCE PLAN</span><h3>Verified tasks and due dates</h3></div><b>{maintenance.length} tasks</b></div><div className="maintenance-list">{maintenance.length ? maintenance.map((task) => <article key={task.id}><span className={task.status}>{task.status}</span><div><b>{task.task}</b><small>{task.interval_months ? `Every ${task.interval_months} months` : "No recurring interval"}{task.next_due ? ` · Next ${task.next_due}` : ""}</small><p>{task.notes || `${task.source_type.replaceAll("_", " ")} source`}</p></div>{task.source_url ? <a href={task.source_url} target="_blank" rel="noreferrer">Source ↗</a> : null}</article>) : <p>No verified maintenance tasks saved yet.</p>}</div>{editable ? <form className="maintenance-form" method="post" action={action}><input type="hidden" name="action" value="maintenance"/><input type="hidden" name="support_session_id" value={supportSessionId}/><input type="hidden" name="return_to" value={returnTo}/><label>Task<input required name="task" list={`tasks-${asset.id}`} placeholder="Pump service, annual PM, battery replacement…"/><datalist id={`tasks-${asset.id}`}><option value="Manufacturer preventive maintenance inspection"/><option value="Fluid and filter service"/><option value="Battery inspection and load test"/><option value="Tire inspection and rotation"/><option value="Pump and aerial system service"/><option value="Calibration / function test"/></datalist></label><label>Source<select name="source_type" defaultValue="manufacturer_manual"><option value="manufacturer_manual">Manufacturer manual</option><option value="service_bulletin">Service bulletin</option><option value="department_plan">Department plan</option><option value="regulatory_standard">Standard / regulation</option><option value="vendor_recommendation">Vendor recommendation</option></select></label><label>Source URL<input type="url" name="source_url" placeholder="https://…"/></label><label>Interval months<input type="number" min="0" max="240" name="interval_months"/></label><label>Last completed<input type="date" name="last_completed"/></label><label>Next due<input type="date" name="next_due"/></label><label>Status<select name="status" defaultValue="planned"><option value="planned">Planned</option><option value="due">Due</option><option value="overdue">Overdue</option><option value="complete">Complete</option></select></label><label className="wide">Notes<textarea name="notes" rows={2} placeholder="Procedure, parts, vendor, or verification note"/></label><button className="wide" type="submit">Add verified maintenance task</button></form> : null}<div className="maintenance-disclaimer">Starter task names are prompts only. Use the reviewed manufacturer manual, approved service bulletin, department policy, or applicable standard to set the actual interval.</div></section>
    {recordMode ? <section className="asset-subsection asset-history"><div className="asset-subhead"><div><span>PERMANENT HISTORY</span><h3>Record activity</h3></div><b>{events.length} entries</b></div>{events.length ? <ol>{events.map((event) => <li key={event.id}><i/><div><b>{event.event_type.replaceAll("_", " ")}</b><p>{event.detail}</p><small>{new Date(event.occurred_at).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}{event.odometer !== null ? ` · Odometer ${event.odometer}` : ""}{event.engine_hours !== null ? ` · Hours ${event.engine_hours}` : ""}</small></div></li>)}</ol> : <p className="asset-history-empty">No history entries have been recorded yet.</p>}</section> : null}
  </div>;
}
